# Generated by Django 3.2.23 on 2023-11-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forla_app', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
