# Generated by Django 3.2.23 on 2023-11-22 02:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forla_app', '0004_producto_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.AddField(
            model_name='producto',
            name='fechaPublicacion',
            field=models.CharField(default=datetime.datetime(2023, 11, 22, 2, 12, 2, 810180, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default=datetime.datetime(2023, 11, 22, 2, 14, 6, 602957, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Forla_SA/media/productos'),
        ),
    ]
